### PR TITLE
feat(generic host): implement UseSignalR for generic host

### PR DESCRIPTION
**Pull request by stephenlautier**
### Features
- Add `UseSignalR` for generic host `ISiloBuilder` - fixes https://github.com/OrleansContrib/SignalR.Orleans/issues/69
- Align both `ISiloBuilder` and `ISiloHostBuilder` - now with `.Configure` instead of `Action` exposed
- Moved `ISiloHostBuilder` extension to the correct namespace

### Deprecated Code
- `SignalrServerConfig` has been marked as Obsolete

### CODE REVIEW

**Comment by stephenlautier** [comment]
@galvesribeiro sorry for closing the other, usually what i do is reset hard on upstream master and i just branch from there. Is that not good?

**Comment by galvesribeiro** [comment]
image

Still outdated. Let me update myself. 1m

**Comment by stephenlautier** [comment]
ahh oki i think i know why im causing it, because im not fetching on upstream 🤦‍♂

**Comment by galvesribeiro** [comment]
thanks!

**Comment by galvesribeiro** [comment]
It is out https://www.nuget.org/packages/SignalR.Orleans/1.3.2

**Pull request merged**
